### PR TITLE
Upgrade to sttp 2.2.9

### PR DESCRIPTION
**Pull request by Fristi**

### CODE REVIEW

**Comment by Fristi** [comment]
Mima is failing, how do we get around that?

**Comment by julienrf** [comment]
We need to bump the version of the sttp interpreter. Just set `version := 2.0.0` in the `sttp-client` build definition.

**Review by julienrf — APPROVED** [review]

**Comment by julienrf** [comment]
Thank you @Fristi !

**Comment by RustamSultanov** [comment]
@Fristi  I work on it too but I try to add crossbuild with scala.js for sttp v2 and I have some difficults for upgrade to sttp v2 version. Thank you for your work.

**Pull request merged**
