### PR TITLE
Update to sjs-dom 2.0.0, laminar 0.14.0

### PR DESCRIPTION
**Pull request by armanbilge**
Supersedes #931 and #940.

### CODE REVIEW

**Comment by armanbilge** [comment]
I think you'll have to bump your version number for the xhr module, but otherwise I think this is good to be merged 👍

**Comment by julienrf** [comment]
May I ask you to relax de compatibility intention in the necessary modules?

**Comment by armanbilge** [comment]
Sure, I'll give a try. Is there a reason to prefer that to bumping the version?

**Comment by julienrf** [comment]
> Is there a reason to prefer that to bumping the version?

Both will go together: we need to indicate that we intend to break the binary compatibility of the impacted modules, and when we will cut the release we will set the module versions accordingly.

**Review by julienrf — APPROVED** [review]

**Comment by armanbilge** [comment]
Ah, thanks for explaining! The tooling I'm used to working with is a bit different, semantic versioning is assumed and compatibility is dictated via the version increment :)

**Comment by julienrf** [comment]
No problem! You can find some more explanations here: https://github.com/endpoints4s/endpoints4s/blob/master/CONTRIBUTING.md#breakage-policy and there: https://github.com/endpoints4s/endpoints4s/blob/master/CONTRIBUTING.md#introduction-of-source-or-binary-incompatibilities

**Pull request merged**
