### PR TITLE
Remove no longer necessary uses of CrossVersion.for3Use2_13

### PR DESCRIPTION
**Pull request by ptrdom**
References https://github.com/endpoints4s/endpoints4s/issues/566.

### CODE REVIEW

**Comment by ptrdom** [comment]
This PR is not that useful:

- `play-json` is still pending a release for Scala 3. Seems like it could be expected relatively soon
- `akka-http` is also pending a release for Scala 3. It also could be expected relatively soon, but it will be only under new BSL license. Relates to https://github.com/endpoints4s/endpoints4s/issues/1103.

**Review by julienrf — APPROVED** [review]
Thank you very much!

I guess we will (unfortunately) have to wait before we can publish the akka-http modules for Scala 3, right?

**Comment by ptrdom** [comment]
> I guess we will (unfortunately) have to wait before we can publish the akka-http modules for Scala 3, right?

Yes, indeed.

**Comment by julienrf** [comment]
I’ve pushed a commit to not publish the Scala 3 modules that still depend on Scala 2.13 artifacts.

I’ve seen there are some errors in the CI, do you know what’s going on?

**Comment by ptrdom** [comment]
I saw some errors in Akka HTTP interpreters related to removal of `CrossVersion.for3Use2_13` for actors and streams, have not looked into the errors further.

**Comment by julienrf** [comment]
Unfortunately, bumping the Scala 3 compiler to 3.2.x does not seem to be easy. I’ve pushed another commit that fixes the CI but I realize that it basically undoes what you previously did: it adds back all the removed `cross(CrossVersion.for3Use2_13)`.

At least that allows us to publish Scala 3 modules for the algebras, the http4s interpreters, and the Scala.js interpreters…

**Comment by ptrdom** [comment]
Yeah, the name of this PR has kind of lost its meaning now 😄 Oh well, we will have a chance to get back to this topic in the future.

**Comment by julienrf** [comment]
What would you like to do? I am fine with waiting a bit longer in case you would be interested in investigating how to use the Scala 3 artifacts of Akka… Otherwise, I am happy to roll a 1.9.0 release of endpoints4s with Scala 3 artifacts for the algebras, the sttp interpreter, the http4s interpreters, and the Scala.js interpreters.

**Comment by ptrdom** [comment]
We can definitely just go forward with 1.9.0 release now, there is not much point in trying to resolve Akka issues at this moment because we are anyways blocked by Akka HTTP.

**Pull request merged**
